version: "3.7"
services:

#Laravel App
  app:
    build:
      args:
        user: Ahmed
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: contacts_ms
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    # networks:
    #   - mynetwork